TrajectoryPlannerROS:
    holonomic_robot: false
<!-- Velocity Parameters -->
    max_vel_x: 2
    min_vel_x: -2
    max_vel_y: 0
    min_vel_y: 0
    max_trans_vel: 0.5
    min_trans_vel: 0.1
    trans_stopped_vel: 0.1
    max_rot_vel: 5
    min_rot_vel: 0.4
    rot_stopped_vel: 0.4
<!-- Acceleration Parameters -->
    acc_lim_x: 2.5
    acc_lim_theta: 2
    acc_lim_y: 0
<!-- Publish trajectories -->
    publish_traj_pc: true
    publish_cost_grid_pc: true
