map_type: costmap

<!-- Range for sensor to read obstacles-->
obstacle_range: 2.5
<!-- Range to raytrace freespace -->
raytrace_range: 3.0
<!-- Delay in TF Data-->
transform_tolerance: 0.5

robot_radius: 0.1
<!-- Radius to which costmap inflates obstacle cost values-->
inflation_radius: 1.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
