global_costmap:
   global_frame: map
   robot_base_frame: robot_footprint
<!-- Map Update frequency-->
   update_frequency: 5.0
   publish_frequency: 2.0
   width: 40.0
   height: 40.0
   resolution: 0.05
<!-- Delay in TF Date -->
   transform_tolerance: 0.5
   static_map: true
   rolling_window: false
